### ISSUE TITLE
Factory Pattern 12, CloseHH/element 10 does not parse...

### ISSUE THREAD

**Issue by mungewell** [mungewell/uno-drum-utils#4]
```
$ hexdump -C temp.bin
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 13 63 64  |..!....7..?. .cd|
00000010  18 09 00 00 00 00 08 05  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000020  7f 7f 7f 7f 7f 7f 00 00  00 f7                    |..........|
0000002a
```

This seems to have an extra byte in it... remove it and I can parse. But why is it there?
```
test = b"\x20 <- last step 32
\x13\x63\x64\x18\x09 <- 14 bits/steps
\x00\x00\x00\x00\x08\x05 <- why is this longer???
\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F <- 14 steps
\x00\x00\x00"
```

**Comment by mungewell** [comment]
Pattern 26 has same feature on element 10
```
Parsing './26.unodrpt'
00000000: 0E 7F 7F 00 01 05 7F 7F  7F 7F 7F 7F 7F 7F 7F 7F  ................
00000010: 7F 7F 7F 7F 00 00 00                              .......
```

The second bitfield has bits, but what meaning?
```
00 01 05
00 08 05
```

**Comment by mungewell** [comment]
For factory 12; this strange parameter exists in the last Closed HH of the sequence, I can delete all other HH steps and it remains.

```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 0a f7' -r temp.bin -t .1 ; hexdump -C temp.bin

29 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 00 00 00  |..!....7..?. ...|
00000010  00 08 00 00 00 00 08 05  7f 00 00 00 f7           |.............|
0000001d
```
But is I delete the last one it goes... even if I re-add set the step. Huh? Is there a way to set an accent on a step??
```
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 00 00 00  |..!....7..?. ...|
00000010  00 08 00 00 00 00 00 7f  00 00 00 f7              |............|
0000001c
```

**Comment by mungewell** [comment]
Modified the pattern so there was a ramp in velocities before the last step/note (with the issue). 
```
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 13 63 64  |..!....7..?. .cd|
00000010  18 09 00 00 00 00 08 05  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000020  7f 7f 1d 46 6c 7f 00 00  00 f7                    |...Fl.....|
0000002a
```

Then recorded the output midi stream to look for difference between 'with' and 'without' feature...
CLOSED HAT: note F#2 (42) = 0x2A.
![Screenshot_2021-01-26_22-11-07](https://user-images.githubusercontent.com/236907/105946047-af884f80-6023-11eb-9cd1-3573a7536599.png)

Appears to be adding an extra note off/note on pair.... is the feature perhaps a short section of stutter/roll?

**Comment by mungewell** [comment]
Timing with feature
```
45947904 + 0: 0x992a7f
45947904 + 0: 0xb91c3e
45948928 + 0: 0xf8
45950976 + 0: 0xf8
45953024 + 0: 0x892a00
45953024 + 0: 0xf8
45953024 + 0: 0x992a7f <- extra on
45955072 + 0: 0xf8
45957120 + 0: 0xf8
45959168 + 0: 0x892a00 <- extra off
45959168 + 0: 0xf8
45959168 + 0: 0x992a7f
45959168 + 0: 0xb91c37
45959168 + 0: 0x99237f
45959168 + 0: 0x99247f
45961216 + 0: 0xf8
45963264 + 0: 0xf8
45965312 + 0: 0x892400
45965312 + 0: 0x892300
```

Timing without feature
```
49081344 + 0: 0x992a7f
49081344 + 0: 0xb91c3e
49083392 + 0: 0xf8
49085440 + 0: 0xf8
49086464 + 0: 0x892a00
49087488 + 0: 0xf8
49089536 + 0: 0xf8
49091584 + 0: 0xf8
49093632 + 0: 0xf8
49093632 + 0: 0x992a7f
49093632 + 0: 0xb91c37
49093632 + 0: 0x99237f
49093632 + 0: 0x99247f
```

**Comment by mungewell** [comment]
Yeap, mute the other elements and delete all but the last step - definitely a double hit played _EVEN_THOUGH_ there is only one entry in the sequence.
```
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 00 00 00  |..!....7..?. ...|
00000010  00 08 00 00 00 00 08 05  7f 00 00 00 f7           |.............|
0000001d
```

**Comment by mungewell** [comment]
Double hit confirm by another user on Reddit.

Looked through some other factory patterns (up-to 75), these are the ones which fail to parse:
12, 26, 44, 46, 57, 26, 72

**Comment by mungewell** [comment]
Pattern 12, line 10
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 0a f7' -r temp.bin -t .1 ; hexdump -C temp.bin

42 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 08 20 13 63 64  |..!....7..?. .cd|
00000010  18 09 00 00 00 00 08 05  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000020  7f 7f 7f 7f 7f 7f 00 00  00 f7                    |..........|
```

Pattern 26, line 10
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 0a f7' -r temp.bin -t .1 ; hexdump -C temp.bin

36 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 0a 3f 0e 0e 7f 7f 00  |..!....7..?.....|
00000010  01 05 7f 7f 7f 7f 7f 7f  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000020  00 00 00 f7                                       |....|
00000024
```

Pattern 44 - something different
```
Parsing '44.unodrpt'
Traceback (most recent call last):
  File "/home/simon/uno-drum-utils-github/decode_pattern.py", line 341, in <module>
    main()
  File "/home/simon/uno-drum-utils-github/decode_pattern.py", line 205, in main
    config = UNODRPT.parse(data)
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 288, in parse
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 300, in parse_stream
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 312, in _parsereport
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 1978, in _parse
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 312, in _parsereport
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 2508, in _parse
construct.core.ConstError: Error in path (parsing)
parsing expected b'8\x00\x01' but parsed b'8\x00\x02'
```

Pattern 46, line 10
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 0a f7' -r temp.bin -t .1 ; hexdump -C temp.bin

30 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 0a 0f 00 10 11 22 03  |..!....7......".|
00000010  00 00 01 05 7f 7f 7f 7f  7f 7f 00 00 00 f7        |..............|
```

Pattern 57, line 4
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 04 f7' -r temp.bin -t .1 ; hexdump -C temp.bin

40 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 04 0b 1e 1e 00 60 00  |..!....7......`.|
00000010  78 03 00 60 00 38 00 05  05 05 05 05 7f 7f 7f 7f  |x..`.8..........|
00000020  7f 7f 7f 7f 00 00 00 f7                           |........|
00000028
```

Pattern 72, line 3
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 03 f7' -r temp.bin -t .1 ; hexdump -C temp.bin

25 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 03 3e 1a 08 40 01 40  |..!....7..>..@.@|
00000010  01 05 05 7f 7f 00 00 00  f7                       |.........|
00000019
```

Patterns 57 and 72 confirm that there can be multiple bytes (not just the one 0x05), so I'll take that as there another variable size array of data - just don't know what it represents... so far the data has always aligned to the velocities.

Seems a logical thought, but enabling a 2nd array in each section blows up other patterns. For example pattern 12 line 8 (kick2) now has a problem. This is step 1 and step 16 with velocity and all 32 steps with varying tuning data.
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 08 f7' -r temp.bin -t .1 ; hexdump -C temp.bin

68 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 08 3f 08 11 01 00 04  |..!....7..?.....|
00000010  00 00 00 7f 7f 00 20 7f  7f 7f 7f 0f 7f 7f 7f 7f  |...... .........|
00000020  0f 37 37 37 37 37 37 37  34 30 30 30 30 30 30 30  |.777777740000000|
00000030  30 35 39 39 39 39 39 43  4e 4e 4e 4e 4b 3f 3f 3f  |0599999CNNNNK???|
00000040  3e 00 00 f7                                       |>...|
00000044
```

So perhaps only the 1st instance (for velocity) can have the extra bytes. Now everything parses OK....

**Comment by mungewell** [comment]
Definately seems to be a 'repeat' or 'roll' setting. For a 'four on the floor' pattern the repeats can be set with:
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 36 03 14 0d 11 22 11 22 01 01 02 01 7f 7f 7f 7f 00 00 00 f7'
                                                                  0^ 0^ 0^ 0^
```


00 or 01 - no repeat
02 or 03 - double repeat, fast
04 - no repeat
05 - double repeat, slower
06 - no repeat
07 or 08 - double repeat, much slower
09 - no repeat
0a - triple repeat, fast
0b - quad repeat, uneven
0c - triple repeat
0d, 0e or 0f - no repeat

High nyble is not stored, ie 11 written => 01 read.

**Comment by mungewell** [comment]
UnoDrum pattern showing this effect...
[ratchet_demo.unodrpt.zip](https://github.com/mungewell/uno-drum-utils/files/6112959/ratchet_demo.unodrpt.zip)

Made with a clear pattern, and then
`$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 36 03 14 0d 11 22 11 22 01 07 05 02 7f 7f 7f 7f 00 00 00 f7'`

**Comment by mungewell** [comment]
The UNO Drum manual says of Roll.

> It is possible to change the roll type up to 4 types: roll 8th note, 8th-note triplets, 16thnote, and
> 32ndnote. After the first rolls, other 4 types called FILLS will be selected. To select a roll type, turn the DATA
> ENCODER while holding the ROLL button. The roll effect is affected by the Swing amount.

And also, but does not explain how.

> A ROLL effects can be recorded in the pattern.

**Comment by mungewell** [comment]
Found that you can be in step editing mode (Rec lit, but play not lit), hold the step and roll buttons, then turn dial... however this would only add a double trigger (as 0x05 in Midi).

Seems that this part of the UI (on device) is not working correctly.

**Comment by mungewell** [comment]
Made some audio recordings...
00 - single
01 - single
02 - double
03 - double
04 - single
05 - double, slower
06 - single
07 - double, even slower
08 - double, even slower
09 - single
0A - triple, slow then fast
0B - quad, fast, slow,slow
0C - triple, fast then slow
0D - single
0E - single
0F - single
[uno-drum-utils-sdw-github.zip](https://github.com/mungewell/uno-drum-utils/files/8723375/uno-drum-utils-sdw-github.zip)
