### ISSUE TITLE
Factory pattern 44 - does not parse

### ISSUE THREAD

**Issue by mungewell** [mungewell/uno-drum-utils#5]
```
$ python3 ~/uno-drum-utils-github/decode_pattern.py -t 44.unodrpt
Parsing '44.unodrpt'
Traceback (most recent call last):
  File "/home/simon/uno-drum-utils-github/decode_pattern.py", line 346, in <module>
    main()
  File "/home/simon/uno-drum-utils-github/decode_pattern.py", line 210, in main
    config = UNODRPT.parse(data)
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 288, in parse
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 300, in parse_stream
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 312, in _parsereport
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 1978, in _parse
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 312, in _parsereport
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.58-py3.6.egg/construct/core.py", line 2508, in _parse
construct.core.ConstError: Error in path (parsing)
parsing expected b'8\x00\x01' but parsed b'8\x00\x02'
```

```
$ hexdump -C 44.unodrpt -v
00000000  55 4e 4f 44 72 75 6d 50  61 74 74 65 72 6e 00 01  |UNODrumPattern..|
00000010  0d 30 00 01 07 05 32 2e  2e 49 43 00 31 00 01 04  |.0....2..IC.1...|
00000020  05 30 2e 00 32 00 01 04  05 30 2e 00 33 00 01 04  |.0..2....0..3...|
00000030  05 30 2e 00 34 00 01 04  05 30 2e 00 35 00 01 04  |.0..4....0..5...|
00000040  05 30 2e 00 36 00 01 24  05 32 33 2e 36 2e 2e 2e  |.0..6..$.23.6...|
00000050  2e 2e 2e 2e 2e 2e 2e 2e  44 2e 2e 2e 2e 2e 2e 2e  |........D.......|
00000060  2e 2e 2e 2e 2e 37 47 2e  2e 2e 2e 00 37 00 01 3d  |.....7G.....7..=|
00000070  05 34 32 2e 38 44 67 48  44 67 50 44 68 50 44 42  |.42.8DgHDgPDhPDB|
00000080  51 2e 2e 2e 2e 2e 2e 2e  2e 2e 2e 2e 2e 37 32 65  |Q............72e|
00000090  2b 38 32 65 2b 38 32 65  2b 38 32 65 2b 38 32 65  |+82e+82e+82e+82e|
000000a0  2b 38 47 2e 2e 2e 2e 2e  2e 2e 2e 2e 00 38 00 02  |+8G..........8..|
000000b0  2a 01 05 32 31 39 2e 38  6a 44 49 6a 48 51 44 49  |*..219.8jDIjHQDI|
000000c0  51 44 49 52 2e 2e 2e 2e  2e 2e 2e 2e 2e 2e 2e 2e  |QDIR............|
000000d0  37 32 65 2b 38 32 65 2b  38 32 65 2b 38 32 65 2b  |72e+82e+82e+82e+|
000000e0  38 32 65 2b 38 32 65 2b  38 32 65 2e 7a 2e 52 6a  |82e+82e+82e.z.Rj|
000000f0  2e 2e 2e 61 55 6c 61 46  41 7a 65 2b 38 32 65 2b  |...aUlaFAze+82e+|
00000100  38 32 65 2b 38 57 2e 2b  38 32 65 2b 38 32 65 2b  |82e+8W.+82e+82e+|
00000110  38 32 65 41 50 42 49 6a  50 42 49 6a 50 42 49 6a  |82eAPBIjPBIjPBIj|
00000120  50 42 49 6a 50 42 49 6b  54 52 49 6b 50 42 49 6a  |PBIjPBIkTRIkPBIj|
00000130  50 42 49 6a 50 42 49 6a  50 42 49 6a 50 42 49 6a  |PBIjPBIjPBIjPBIj|
00000140  50 42 49 6a 72 78 4a 71  72 78 4a 6f 62 52 49 6b  |PBIjrxJqrxJobRIk|
00000150  54 52 49 6b 54 52 49 6b  54 52 49 6a 50 42 49 6a  |TRIkTRIkTRIjPBIj|
00000160  50 42 49 6a 50 42 49 6a  50 42 50 2b 38 32 65 2b  |PBIjPBIjPBP+82e+|
00000170  38 32 65 2b 38 32 65 41  37 32 65 2b 38 32 65 2b  |82e+82eA72e+82e+|
00000180  38 32 65 2b 45 50 47 2e  2e 50 2e 41 44 50 2e 41  |82e+EPG..P.ADP.A|
00000190  44 50 2e 41 44 50 2e 41  44 50 2e 41 44 50 2e 41  |DP.ADP.ADP.ADP.A|
000001a0  44 50 2e 41 44 50 2e 41  44 50 2e 41 44 50 2e 41  |DP.ADP.ADP.ADP.A|
000001b0  44 50 2e 41 44 2e 2e 2e  2e 2e 2e 2e 2e 2e 2e 2e  |DP.AD...........|
000001c0  2e 2e 2e 2e 2e 2e 2e 2e  2e 2e 2e 2e 2e 2e 2e 2e  |................|
000001d0  2e 2e 2e 2e 2e 2e 2e 2e  2e 2e 2e 00 39 00 01 30  |............9..0|
000001e0  05 33 32 2e 38 2e 41 48  2e 41 50 2e 42 50 2e 42  |.32.8.AH.AP.BP.B|
000001f0  50 2e 2e 2e 2e 2e 2e 2e  2e 2e 2e 2e 2e 37 32 65  |P............72e|
00000200  2b 38 32 65 2b 38 32 65  2e 2e 2e 2e 2e 2e 2e 00  |+82e+82e........|
00000210  31 30 00 01 4f 05 35 35  2e 2b 54 45 4a 65 6b 53  |10..O.55.+TEJekS|
00000220  56 4a 49 45 4d 56 41 2e  2e 2e 2e 2e 2e 2e 2e 2e  |VJIEMVA.........|
00000230  2e 2e 37 32 65 2b 6b 6c  62 67 77 6c 64 6f 45 47  |..72e+klbgwldoEG|
00000240  59 77 45 32 61 6a 30 47  62 30 63 32 65 2b 38 32  |YwE2aj0Gb0c2e+82|
00000250  58 66 6b 31 58 2b 38 32  65 6e 6b 57 58 76 41 2e  |Xfk1X+82enkWXvA.|
00000260  2e 2e 2e 00 31 31 00 01  4b 05 35 32 2e 39 37 54  |....11..K.52.97T|
00000270  50 43 55 69 47 7a 45 51  4d 76 2e 2e 2e 2e 2e 2e  |PCUiGzEQMv......|
00000280  2e 2e 2e 2e 2e 2e 6e 57  64 70 41 56 65 6b 41 6d  |......nWdpAVekAm|
00000290  61 66 59 31 59 66 30 6c  64 38 34 56 63 2b 63 6c  |afY1Yf0ld84Vc+cl|
000002a0  62 7a 59 31 65 73 45 46  63 6f 6f 57 58 70 41 2e  |bzY1esEFcooWXpA.|
000002b0  2e 2e 2e 00 31 32 00 01  2b 05 32 38 2e 38 2e 2e  |....12..+.28.8..|
000002c0  2e 2e 41 50 2e 42 50 2e  42 50 2e 2e 2e 2e 2e 2e  |..AP.BP.BP......|
000002d0  2e 2e 2e 2e 2e 2e 37 32  65 2b 38 32 65 2b 41 2e  |......72e+82e+A.|
000002e0  2e 2e 2e 00 00                                    |.....|
000002e5
```

**Comment by mungewell** [comment]
```
000000a0  2b 38 47 2e 2e 2e 2e 2e  2e 2e 2e 2e 00 38 00 02  |+8G..........8..|
                                                  ^^ ^^ ^^
```

```
UNODRPT = Struct(
    Const(b"UNODrumPattern"),
    Const(b"\x00\x01\x0d"),
    Const(b"\x30\x00\x01"), "line0" / BLOB,
    Const(b"\x31\x00\x01"), "line1" / BLOB,
    Const(b"\x32\x00\x01"), "line2" / BLOB,
    Const(b"\x33\x00\x01"), "line3" / BLOB,
    Const(b"\x34\x00\x01"), "line4" / BLOB,
    Const(b"\x35\x00\x01"), "line5" / BLOB,
    Const(b"\x36\x00\x01"), "line6" / BLOB,
    Const(b"\x37\x00\x01"), "line7" / BLOB,
    Const(b"\x38\x00\x01"), "line8" / BLOB,
    #                 ^^
    Const(b"\x39\x00\x01"), "line9" / BLOB,
    Const(b"\x31\x30\x00\x01"), "line10" / BLOB,
    Const(b"\x31\x31\x00\x01"), "line11" / BLOB,
    Const(b"\x31\x32\x00\x01"), "line12" / BLOB,
    Const(b"\x00"),
)
```

**Comment by mungewell** [comment]
```
$ amidi -p hw:2,0,0 -S 'f0 00 21 1a 02 02 37 03 08 f7' -r temp.bin -t .1 ; hexdump -C temp.bin

232 bytes read
00000000  f0 00 21 1a 02 02 00 37  03 08 3f 40 3d 49 24 24  |..!....7..?@=I$$|
00000010  12 11 49 44 24 12 00 00  00 00 00 00 00 00 00 7f  |..ID$...........|
00000020  7f 7f 7f 7f 7f 7f 7f 7f  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000030  7f 7f 7f 00 0d 48 24 00  00 5b 65 6e 46 40 7f 7f  |.....H$..[enF@..|
00000040  7f 7f 7f 7f 7f 7f 7f 01  7f 7f 7f 7f 7f 7f 7f 7f  |................|
00000050  7f 01 24 24 24 24 24 24  24 24 24 24 24 24 24 24  |..$$$$$$$$$$$$$$|
00000060  25 25 25 25 24 24 24 24  24 24 24 24 24 24 24 24  |%%%%$$$$$$$$$$$$|
00000070  24 24 24 24 24 24 2b 2b  2b 2b 2b 29 27 25 25 25  |$$$$$$+++++)'%%%|
00000080  25 25 25 25 25 25 25 24  24 24 24 24 24 24 24 24  |%%%%%%%$$$$$$$$$|
00000090  24 24 40 7f 7f 7f 7f 7f  7f 7f 7f 7f 01 7f 7f 7f  |$$@.............|
000000a0  7f 7f 7f 7f 7f 7f 01 1d  00 00 01 01 01 01 01 01  |................|
000000b0  01 01 01 01 01 01 01 01  01 01 01 01 01 01 01 01  |................|
000000c0  01 01 01 01 01 01 01 01  01 01 01 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 f7                           |........|
000000e8
```

**Comment by mungewell** [comment]
The length of the 'Blob' can be Byte or Short, and this is what the '0x02' is indicating... how wide the length is.

```
$ python3 decode_pattern.py -d Presets/Patterns/44.unodrpt
Parsing 'Presets/Patterns/44.unodrpt'
Container: 
...
    line8 = Container: 
        width = 2
        length = 298
        blob = b'\x05219.8jDIjHQDIQD'... (truncated, total 297)
```

Fixed.
